### PR TITLE
New repo 

### PR DESCRIPTION
**Pull request by mosidrum**
**Added validation code**
**modal popup
email verification**

### CODE REVIEW

**Comment by mosidrum** [comment]
Capture
The icons are showing perfectly

**Comment by mosidrum** [comment]
Capture
Please the icons are displaying from my code base

**Comment by mosidrum** [comment]
Capture2
Please the footer icons too are displaying

**Review by nicupop729 — COMMENTED** [review]
Hello @mosidrum 👋,

_This is an additional review as a result of the second opinion request._

Kudos for making the corrections asked in the first review! :clap:

Please note that the icons are not yet displayed, and we have to make sure that the app is working on the user's system and not only on the personal system. 
You have to correct the path, as I stated in the prior review. At the moment you have it `src="./assets/GroupI.png"` when you should have it `src="./Assets/GroupI.png"`. Keep in mind that your Assets folder is with capital letter.

But because the aspect about the social icons was just an optional requirement, your project is APPROVED.

Keep rocking 🚀!

**Comment by mosidrum** [comment]
Thank you so much, I have renamed the folder from "Assets" to "assets"

**Pull request merged**
